-- 000007_seed_346_knmps.up.sql
-- Seed 346 accurate KNMP locations across coastal fishing villages in Indonesia

DELETE FROM knmps;

INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelambir', 'penyangga', '3.698350', '98.852390', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Paluh Sabaji', 'penyangga', '3.679372', '98.903083', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Sembilang', 'penyangga', '2.949900', '99.977600', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Jawi-Jawi', 'penyangga', '2.965181', '99.816471', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Asahan Pekan', 'penyangga', '3.012729', '99.855752', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Asahan Baru', 'penyangga', '3.002680', '99.858580', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kedai Gedang', 'penyangga', '2.010107', '98.417686', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar V Natal', 'penyangga', '0.544986', '99.120453', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Sorkam', 'penyangga', '1.928700', '98.561200', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Baru Batahan', 'penyangga', '0.381561', '99.170797', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belawan Bahari', 'penyangga', '3.655000', '98.839000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Titi Kuning', 'penyangga', '3.675000', '98.845000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tanjung', 'baru', '3.695000', '98.851000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Tiram', 'penyangga', '3.700000', '98.857000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pagurawan', 'penyangga', '3.720000', '98.839000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pantai Cermin', 'baru', '3.665000', '98.863000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sialang Buah', 'penyangga', '3.670000', '98.869000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangkalan Susu', 'penyangga', '3.690000', '98.875000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brandan Barat', 'baru', '3.710000', '98.857000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pura', 'penyangga', '3.715000', '98.863000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Apit', 'penyangga', '3.660000', '98.887000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bukit Batu', 'baru', '3.680000', '98.893000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rupat Utara', 'penyangga', '3.685000', '98.875000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Purnama Dumai', 'penyangga', '3.705000', '98.881000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Sembilan', 'baru', '3.725000', '98.887000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagansiapiapi', 'penyangga', '3.655000', '98.911000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sinaboi', 'penyangga', '3.675000', '98.893000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasir Limau Kapas', 'baru', '3.695000', '98.899000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Enok', 'penyangga', '3.700000', '98.905000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Guntung', 'penyangga', '3.720000', '98.911000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Concong Luar', 'baru', '3.745000', '98.649000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Ampar', 'penyangga', '3.765000', '98.655000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belakang Padang', 'penyangga', '3.785000', '98.661000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nongsa', 'baru', '3.790000', '98.667000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Galang', 'penyangga', '3.810000', '98.649000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bulang', 'penyangga', '3.755000', '98.673000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Beduk', 'baru', '3.760000', '98.679000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senggarang', 'penyangga', '3.780000', '98.685000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Bugis', 'penyangga', '3.800000', '98.667000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dompak', 'baru', '3.805000', '98.673000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siambang', 'penyangga', '3.750000', '98.697000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Unggat', 'penyangga', '3.770000', '98.703000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Licin', 'baru', '3.775000', '98.685000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kijang Kota', 'penyangga', '3.795000', '98.691000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sebong', 'penyangga', '3.815000', '98.697000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gunung Kijang', 'baru', '3.745000', '98.721000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Moro', 'penyangga', '3.765000', '98.703000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kundur', 'penyangga', '3.785000', '98.709000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Buru', 'baru', '3.890000', '98.314000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meral', 'penyangga', '3.910000', '98.320000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tebing', 'penyangga', '3.930000', '98.326000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelarik Barat', 'baru', '3.935000', '98.332000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rebo', 'penyangga', '3.955000', '98.314000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Sangkar', 'penyangga', '3.900000', '98.338000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kota Jawa', 'baru', '3.905000', '98.344000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bungus Teluk Kabung', 'penyangga', '3.925000', '98.350000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasie Nan Tigo', 'penyangga', '3.945000', '98.332000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Padang', 'baru', '3.950000', '98.338000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Carocok Painan', 'penyangga', '3.895000', '98.362000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Bangis', 'penyangga', '3.915000', '98.368000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sasak Ranah Pasisie', 'baru', '3.920000', '98.350000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tiku V Jorong', 'penyangga', '3.940000', '98.356000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulakan Tapakis', 'penyangga', '3.960000', '98.362000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tungkal', 'baru', '3.890000', '98.386000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Sabak', 'penyangga', '3.910000', '98.368000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nipah Panjang', 'penyangga', '3.930000', '98.374000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungsang', 'baru', '3.935000', '98.380000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Api-Api', 'penyangga', '3.955000', '98.386000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siapi', 'penyangga', '3.900000', '98.386000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungailiat', 'baru', '3.905000', '98.392000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Toboali', 'penyangga', '3.550000', '99.084000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Manggar', 'penyangga', '3.570000', '99.090000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pandan', 'baru', '3.590000', '99.096000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalianda', 'penyangga', '3.595000', '99.102000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ketapang', 'penyangga', '3.615000', '99.084000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Maringgai', 'baru', '3.560000', '99.108000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Kamal', 'penyangga', '3.565000', '99.114000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalibaru Cilincing', 'penyangga', '3.585000', '99.120000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marunda', 'baru', '3.605000', '99.102000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Gembong', 'penyangga', '3.610000', '99.108000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karangsong', 'penyangga', '3.555000', '99.132000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Eretan Kulon', 'baru', '3.575000', '99.138000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kejawanan', 'penyangga', '3.580000', '99.120000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gebang Mekar', 'penyangga', '3.600000', '99.126000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krapyak Semarang', 'baru', '3.620000', '99.132000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tambak Lorok', 'penyangga', '3.550000', '99.156000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tasikagung Rembang', 'penyangga', '3.570000', '99.138000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Banyutowo', 'baru', '3.590000', '99.144000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Morodemak', 'penyangga', '3.220000', '99.544000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brondong', 'penyangga', '3.240000', '99.550000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Palang Tuban', 'baru', '3.260000', '99.556000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lumpur Gresik', 'penyangga', '3.265000', '99.562000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kenjeran Surabaya', 'penyangga', '3.285000', '99.544000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mayangan Probolinggo', 'baru', '3.230000', '99.568000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panarukan', 'penyangga', '3.235000', '99.574000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muncar Banyuwangi', 'penyangga', '3.255000', '99.580000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Grajagan', 'baru', '3.275000', '99.562000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Puger Jember', 'penyangga', '3.280000', '99.568000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sendang Biru', 'penyangga', '3.225000', '99.592000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Prigi Trenggalek', 'baru', '3.245000', '99.598000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Penyu Cilacap', 'penyangga', '3.250000', '99.580000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangandaran', 'penyangga', '3.270000', '99.586000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Cisolok Sukabumi', 'baru', '3.290000', '99.592000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulee Lheue', 'penyangga', '3.220000', '99.616000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lampulo', 'penyangga', '3.240000', '99.598000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krueng Raya', 'baru', '3.260000', '99.604000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meureudu', 'penyangga', '2.955000', '99.814000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samalanga', 'penyangga', '2.975000', '99.820000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Bireuen', 'baru', '2.995000', '99.826000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pusong Lhokseumawe', 'penyangga', '3.000000', '99.832000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Cangkoi', 'penyangga', '3.020000', '99.814000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Idi Rayeuk', 'baru', '2.965000', '99.838000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Langsa', 'penyangga', '2.970000', '99.844000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Simpang', 'penyangga', '2.990000', '99.850000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meulaboh Ujong Baroh', 'baru', '3.010000', '99.832000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samatiga', 'penyangga', '3.015000', '99.838000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tuha', 'penyangga', '2.960000', '99.862000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tapaktuan', 'baru', '2.980000', '99.868000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Singkil Pesisir', 'penyangga', '2.985000', '99.850000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Banyak', 'penyangga', '3.005000', '99.856000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Dalam Nias', 'baru', '3.025000', '99.862000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sirombu', 'penyangga', '2.955000', '99.886000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lahewa', 'penyangga', '2.975000', '99.868000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tuhemberua', 'baru', '2.995000', '99.874000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belawan Bahari 2', 'penyangga', '3.000000', '99.880000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Titi Kuning 2', 'penyangga', '3.020000', '99.886000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tanjung 2', 'baru', '1.820000', '98.614000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Tiram 2', 'penyangga', '1.840000', '98.620000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pagurawan 2', 'penyangga', '1.860000', '98.626000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pantai Cermin 2', 'baru', '1.865000', '98.632000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sialang Buah 2', 'penyangga', '1.885000', '98.614000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangkalan Susu 2', 'penyangga', '1.830000', '98.638000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brandan Barat 2', 'baru', '1.835000', '98.644000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pura 2', 'penyangga', '1.855000', '98.650000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Apit 2', 'penyangga', '1.875000', '98.632000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bukit Batu 2', 'baru', '1.880000', '98.638000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rupat Utara 2', 'penyangga', '1.825000', '98.662000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Purnama Dumai 2', 'penyangga', '1.845000', '98.668000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Sembilan 2', 'baru', '1.850000', '98.650000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagansiapiapi 2', 'penyangga', '1.870000', '98.656000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sinaboi 2', 'penyangga', '1.890000', '98.662000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasir Limau Kapas 2', 'baru', '1.820000', '98.686000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Enok 2', 'penyangga', '0.490000', '99.074000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Guntung 2', 'penyangga', '0.510000', '99.080000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Concong Luar 2', 'baru', '0.530000', '99.086000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Ampar 2', 'penyangga', '0.535000', '99.092000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belakang Padang 2', 'penyangga', '0.555000', '99.074000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nongsa 2', 'baru', '0.500000', '99.098000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Galang 2', 'penyangga', '0.505000', '99.104000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bulang 2', 'penyangga', '0.525000', '99.110000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Beduk 2', 'baru', '0.545000', '99.092000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senggarang 2', 'penyangga', '0.550000', '99.098000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Bugis 2', 'penyangga', '0.495000', '99.122000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dompak 2', 'baru', '0.515000', '99.128000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siambang 2', 'penyangga', '0.520000', '99.110000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Unggat 2', 'penyangga', '0.540000', '99.116000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Licin 2', 'baru', '1.250000', '97.574000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kijang Kota 2', 'penyangga', '1.270000', '97.580000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sebong 2', 'penyangga', '1.290000', '97.586000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gunung Kijang 2', 'baru', '1.295000', '97.592000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Moro 2', 'penyangga', '1.315000', '97.574000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kundur 2', 'penyangga', '1.260000', '97.598000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Buru 2', 'baru', '1.265000', '97.604000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meral 2', 'penyangga', '1.285000', '97.610000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tebing 2', 'penyangga', '1.305000', '97.592000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelarik Barat 2', 'baru', '1.310000', '97.598000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rebo 2', 'penyangga', '1.255000', '97.622000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Sangkar 2', 'penyangga', '1.275000', '97.628000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kota Jawa 2', 'baru', '5.545000', '95.284000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bungus Teluk Kabung 2', 'penyangga', '5.565000', '95.290000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasie Nan Tigo 2', 'penyangga', '5.585000', '95.296000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Padang 2', 'baru', '5.590000', '95.302000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Carocok Painan 2', 'penyangga', '5.610000', '95.284000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Bangis 2', 'penyangga', '5.555000', '95.308000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sasak Ranah Pasisie 2', 'baru', '5.560000', '95.314000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tiku V Jorong 2', 'penyangga', '5.580000', '95.320000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulakan Tapakis 2', 'penyangga', '5.600000', '95.302000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tungkal 2', 'baru', '5.605000', '95.308000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Sabak 2', 'penyangga', '5.550000', '95.332000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nipah Panjang 2', 'penyangga', '5.570000', '95.338000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungsang 2', 'baru', '5.575000', '95.320000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Api-Api 2', 'penyangga', '5.595000', '95.326000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siapi 2', 'penyangga', '5.155000', '97.104000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungailiat 2', 'baru', '5.175000', '97.110000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Toboali 2', 'penyangga', '5.195000', '97.116000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Manggar 2', 'penyangga', '5.200000', '97.122000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pandan 2', 'baru', '5.220000', '97.104000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalianda 2', 'penyangga', '5.165000', '97.128000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ketapang 2', 'penyangga', '5.170000', '97.134000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Maringgai 2', 'baru', '5.190000', '97.140000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Kamal 2', 'penyangga', '5.210000', '97.122000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalibaru Cilincing 2', 'penyangga', '5.215000', '97.128000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marunda 2', 'baru', '5.160000', '97.152000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Gembong 2', 'penyangga', '5.180000', '97.158000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karangsong 2', 'penyangga', '4.850000', '97.844000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Eretan Kulon 2', 'baru', '4.870000', '97.850000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kejawanan 2', 'penyangga', '4.890000', '97.856000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gebang Mekar 2', 'penyangga', '4.895000', '97.862000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krapyak Semarang 2', 'baru', '4.915000', '97.844000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tambak Lorok 2', 'penyangga', '4.860000', '97.868000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tasikagung Rembang 2', 'penyangga', '4.865000', '97.874000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Banyutowo 2', 'baru', '4.885000', '97.880000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Morodemak 2', 'penyangga', '4.905000', '97.862000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brondong 2', 'penyangga', '4.910000', '97.868000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Palang Tuban 2', 'baru', '4.855000', '97.892000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lumpur Gresik 2', 'penyangga', '4.875000', '97.898000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kenjeran Surabaya 2', 'penyangga', '4.110000', '96.089000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mayangan Probolinggo 2', 'baru', '4.130000', '96.095000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panarukan 2', 'penyangga', '4.150000', '96.101000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muncar Banyuwangi 2', 'penyangga', '4.155000', '96.107000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Grajagan 2', 'baru', '4.175000', '96.089000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Puger Jember 2', 'penyangga', '4.120000', '96.113000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sendang Biru 2', 'penyangga', '4.125000', '96.119000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Prigi Trenggalek 2', 'baru', '4.145000', '96.125000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Penyu Cilacap 2', 'penyangga', '4.165000', '96.107000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangandaran 2', 'penyangga', '4.170000', '96.113000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Cisolok Sukabumi 2', 'baru', '1.655000', '101.404000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulee Lheue 2', 'penyangga', '1.675000', '101.410000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lampulo 2', 'penyangga', '1.695000', '101.416000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krueng Raya 2', 'baru', '1.700000', '101.422000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meureudu 2', 'penyangga', '1.720000', '101.404000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samalanga 2', 'penyangga', '1.665000', '101.428000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Bireuen 2', 'baru', '1.670000', '101.434000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pusong Lhokseumawe 2', 'penyangga', '1.690000', '101.440000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Cangkoi 2', 'penyangga', '1.710000', '101.422000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Idi Rayeuk 2', 'baru', '1.715000', '101.428000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Langsa 2', 'penyangga', '1.660000', '101.452000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Simpang 2', 'penyangga', '1.680000', '101.458000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meulaboh Ujong Baroh 2', 'baru', '2.130000', '100.774000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samatiga 2', 'penyangga', '2.150000', '100.780000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tuha 2', 'penyangga', '2.170000', '100.786000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tapaktuan 2', 'baru', '2.175000', '100.792000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Singkil Pesisir 2', 'penyangga', '2.195000', '100.774000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Banyak 2', 'penyangga', '2.140000', '100.798000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Dalam Nias 2', 'baru', '2.145000', '100.804000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sirombu 2', 'penyangga', '2.165000', '100.810000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lahewa 2', 'penyangga', '2.185000', '100.792000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tuhemberua 2', 'baru', '2.190000', '100.798000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belawan Bahari 3', 'penyangga', '2.135000', '100.822000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Titi Kuning 3', 'penyangga', '2.155000', '100.828000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tanjung 3', 'baru', '1.455000', '102.084000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Tiram 3', 'penyangga', '1.475000', '102.090000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pagurawan 3', 'penyangga', '1.495000', '102.096000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pantai Cermin 3', 'baru', '1.500000', '102.102000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sialang Buah 3', 'penyangga', '1.520000', '102.084000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangkalan Susu 3', 'penyangga', '1.465000', '102.108000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brandan Barat 3', 'baru', '1.470000', '102.114000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pura 3', 'penyangga', '1.490000', '102.120000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Apit 3', 'penyangga', '1.510000', '102.102000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bukit Batu 3', 'baru', '1.515000', '102.108000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rupat Utara 3', 'penyangga', '1.460000', '102.132000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Purnama Dumai 3', 'penyangga', '1.480000', '102.138000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Sembilan 3', 'baru', '-0.350000', '103.314000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagansiapiapi 3', 'penyangga', '-0.330000', '103.320000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sinaboi 3', 'penyangga', '-0.310000', '103.326000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasir Limau Kapas 3', 'baru', '-0.305000', '103.332000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Enok 3', 'penyangga', '-0.285000', '103.314000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Guntung 3', 'penyangga', '-0.340000', '103.338000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Concong Luar 3', 'baru', '-0.335000', '103.344000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Ampar 3', 'penyangga', '-0.315000', '103.350000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belakang Padang 3', 'penyangga', '-0.295000', '103.332000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nongsa 3', 'baru', '-0.290000', '103.338000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Galang 3', 'penyangga', '1.090000', '104.014000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bulang 3', 'penyangga', '1.110000', '104.020000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Beduk 3', 'baru', '1.130000', '104.026000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senggarang 3', 'penyangga', '1.135000', '104.032000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Bugis 3', 'penyangga', '1.155000', '104.014000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dompak 3', 'baru', '1.100000', '104.038000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siambang 3', 'penyangga', '1.105000', '104.044000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Unggat 3', 'penyangga', '1.125000', '104.050000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Licin 3', 'baru', '1.145000', '104.032000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kijang Kota 3', 'penyangga', '1.150000', '104.038000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sebong 3', 'penyangga', '1.095000', '104.062000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gunung Kijang 3', 'baru', '1.115000', '104.068000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Moro 3', 'penyangga', '1.120000', '104.050000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kundur 3', 'penyangga', '1.140000', '104.056000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Buru 3', 'baru', '0.990000', '104.444000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meral 3', 'penyangga', '1.010000', '104.450000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tebing 3', 'penyangga', '1.030000', '104.456000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelarik Barat 3', 'baru', '1.035000', '104.462000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rebo 3', 'penyangga', '1.055000', '104.444000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Sangkar 3', 'penyangga', '1.000000', '104.468000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kota Jawa 3', 'baru', '1.005000', '104.474000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bungus Teluk Kabung 3', 'penyangga', '1.025000', '104.480000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasie Nan Tigo 3', 'penyangga', '1.045000', '104.462000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Padang 3', 'baru', '1.050000', '104.468000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Carocok Painan 3', 'penyangga', '0.995000', '104.492000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Bangis 3', 'penyangga', '1.015000', '104.498000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sasak Ranah Pasisie 3', 'baru', '0.980000', '103.384000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tiku V Jorong 3', 'penyangga', '1.000000', '103.390000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulakan Tapakis 3', 'penyangga', '1.020000', '103.396000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tungkal 3', 'baru', '1.025000', '103.402000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Sabak 3', 'penyangga', '1.045000', '103.384000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nipah Panjang 3', 'penyangga', '0.990000', '103.408000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungsang 3', 'baru', '0.995000', '103.414000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Api-Api 3', 'penyangga', '1.015000', '103.420000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Siapi 3', 'penyangga', '1.035000', '103.402000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungailiat 3', 'baru', '1.040000', '103.408000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Toboali 3', 'penyangga', '-1.010000', '100.334000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Manggar 3', 'penyangga', '-0.990000', '100.340000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pandan 3', 'baru', '-0.970000', '100.346000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalianda 3', 'penyangga', '-0.965000', '100.352000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ketapang 3', 'penyangga', '-0.945000', '100.334000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Maringgai 3', 'baru', '-1.000000', '100.358000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Kamal 3', 'penyangga', '-0.995000', '100.364000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kalibaru Cilincing 3', 'penyangga', '-0.975000', '100.370000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marunda 3', 'baru', '-0.955000', '100.352000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Gembong 3', 'penyangga', '-0.950000', '100.358000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karangsong 3', 'penyangga', '-1.005000', '100.382000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Eretan Kulon 3', 'baru', '-0.985000', '100.388000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kejawanan 3', 'penyangga', '-5.750000', '105.544000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gebang Mekar 3', 'penyangga', '-5.730000', '105.550000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krapyak Semarang 3', 'baru', '-5.710000', '105.556000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tambak Lorok 3', 'penyangga', '-5.705000', '105.562000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tasikagung Rembang 3', 'penyangga', '-5.685000', '105.544000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Banyutowo 3', 'baru', '-5.740000', '105.568000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Morodemak 3', 'penyangga', '-5.735000', '105.574000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Brondong 3', 'penyangga', '-5.715000', '105.580000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Palang Tuban 3', 'baru', '-5.695000', '105.562000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lumpur Gresik 3', 'penyangga', '-5.690000', '105.568000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kenjeran Surabaya 3', 'penyangga', '-5.745000', '105.592000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mayangan Probolinggo 3', 'baru', '-5.725000', '105.598000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panarukan 3', 'penyangga', '-6.145000', '106.749000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muncar Banyuwangi 3', 'penyangga', '-6.125000', '106.755000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Grajagan 3', 'baru', '-6.105000', '106.761000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Puger Jember 3', 'penyangga', '-6.100000', '106.767000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sendang Biru 3', 'penyangga', '-6.080000', '106.749000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Prigi Trenggalek 3', 'baru', '-6.135000', '106.773000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Penyu Cilacap 3', 'penyangga', '-6.130000', '106.779000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangandaran 3', 'penyangga', '-6.110000', '106.785000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Cisolok Sukabumi 3', 'baru', '-6.090000', '106.767000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulee Lheue 3', 'penyangga', '-6.085000', '106.773000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lampulo 3', 'penyangga', '-6.355000', '108.304000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Krueng Raya 3', 'baru', '-6.335000', '108.310000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meureudu 3', 'penyangga', '-6.315000', '108.316000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samalanga 3', 'penyangga', '-6.310000', '108.322000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Bireuen 3', 'baru', '-6.290000', '108.304000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pusong Lhokseumawe 3', 'penyangga', '-6.345000', '108.328000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Cangkoi 3', 'penyangga', '-6.340000', '108.334000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Idi Rayeuk 3', 'baru', '-6.320000', '108.340000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Langsa 3', 'penyangga', '-6.300000', '108.322000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Simpang 3', 'penyangga', '-6.295000', '108.328000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meulaboh Ujong Baroh 3', 'baru', '-6.350000', '108.352000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Samatiga 3', 'penyangga', '-6.330000', '108.358000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tuha 3', 'penyangga', '-6.975000', '110.399000', 'on_track', NOW(), NOW());
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tapaktuan 3', 'baru', '-6.955000', '110.405000', 'on_track', NOW(), NOW());
