-- 000001_init_all_schema_and_seeds.down.sql

DROP TABLE IF EXISTS message_reads CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversation_members CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;

DROP TABLE IF EXISTS verifications CASCADE;
DROP TABLE IF EXISTS documents CASCADE;

DROP TABLE IF EXISTS pembayarans CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS absensis CASCADE;
DROP TABLE IF EXISTS laporan_details CASCADE;
DROP TABLE IF EXISTS laporans CASCADE;
DROP TABLE IF EXISTS pelaksanaans CASCADE;
DROP TABLE IF EXISTS pcms CASCADE;
DROP TABLE IF EXISTS persiapans CASCADE;

DROP TABLE IF EXISTS user_has_knmps CASCADE;
DROP TABLE IF EXISTS knmps CASCADE;
DROP TABLE IF EXISTS desas CASCADE;
DROP TABLE IF EXISTS kecamatans CASCADE;
DROP TABLE IF EXISTS kabupatens CASCADE;
DROP TABLE IF EXISTS provinsis CASCADE;
DROP TABLE IF EXISTS periodes CASCADE;
DROP TABLE IF EXISTS jenis_bangunans CASCADE;

DROP TABLE IF EXISTS role_has_permissions CASCADE;
DROP TABLE IF EXISTS model_has_roles CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
