INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Alue Naga', 'penyangga', '5.596292', '95.351014', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batee Shoek', 'penyangga', '5.841301', '95.292045', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Keuneukai', 'penyangga', '5.776228', '95.319651', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Jaboi', 'penyangga', '5.800060', '95.343689', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Layeun', 'penyangga', '5.346805', '95.240348', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Leungah', 'penyangga', '5.560570', '95.718445', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kareung', 'penyangga', '5.301834', '95.241687', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Keurisi Meunasah Beureumbang', 'penyangga', '5.213196', '96.325985', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meunasah Jurong', 'penyangga', '5.255703', '96.261362', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasi Beurandeh', 'penyangga', '5.437791', '95.897782', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Pidie', 'penyangga', '5.388111', '95.963428', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Jeumeurang', 'penyangga', '5.294622', '96.073341', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjong Kreueng', 'penyangga', '5.320008', '96.037016', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lapang Barat', 'penyangga', '5.242016', '96.884540', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Ceurape', 'penyangga', '5.265283', '96.843551', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lancang', 'penyangga', '5.197543', '96.507087', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Matang Pasi', 'penyangga', '5.207925', '96.595384', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Geulumpang Sulu Timu', 'penyangga', '5.251795', '96.995397', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala', 'penyangga', '5.144751', '97.152406', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ujong Blang', 'penyangga', '5.205898', '97.117774', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulee Rubek Timu', 'penyangga', '5.217930', '97.424185', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ulee Rubek Barat', 'penyangga', '5.209483', '97.410561', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Matang Puntong', 'penyangga', '5.188543', '97.360979', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Cangkoy', 'penyangga', '5.170944', '97.304385', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Pusung Kapal', 'penyangga', '4.396087', '98.263230', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gampong Kuala', 'penyangga', '4.908169', '97.839319', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Paya Dua', 'penyangga', '4.901531', '97.838484', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gampong Aceh', 'penyangga', '4.953617', '97.772794', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Langsa', 'penyangga', '4.514050', '98.013605', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Tarok li', 'penyangga', '3.440055', '97.068657', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ujong Pulo Rayeuk', 'penyangga', '3.118700', '97.311200', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sawang Indah', 'penyangga', '3.550560', '97.039090', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Darul Ikhsan', 'penyangga', '2.956487', '97.418400', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Nibung', 'penyangga', '2.360603', '97.415277', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Paton Makmur', 'penyangga', '4.649753', '95.597206', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ujong Muloh', 'penyangga', '5.053278', '95.337249', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gle Jong', 'penyangga', '5.109910', '95.374120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Suak Seumaseh', 'penyangga', '4.273132', '95.974595', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Padang Seurahet', 'penyangga', '4.142526', '96.138508', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Tadu', 'penyangga', '3.965863', '96.312550', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ujung Tanaoh', 'penyangga', '3.690259', '96.872159', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Padang Baru', 'penyangga', '3.724050', '96.812500', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Lugu Sekbahak', 'penyangga', '2.684270', '96.103487', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Aman', 'penyangga', '2.699410', '96.163410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sambay', 'penyangga', '2.702910', '96.150410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Ale', 'penyangga', '2.627523', '95.967065', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kahad', 'penyangga', '2.365395', '96.333057', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Langi', 'penyangga', '2.833140', '95.901120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Amaiteng Mulia', 'penyangga', '2.485700', '96.370499', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nasreuhe', 'penyangga', '2.765410', '95.935120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Latiung', 'penyangga', '2.357417', '96.452420', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sigulai', 'penyangga', '2.742188', '95.915662', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Way Hawang', 'penyangga', '-4.865063', '103.434649', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Lama', 'penyangga', '-4.798498', '103.350294', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pandan', 'penyangga', '-4.702434', '103.287871', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Pino', 'penyangga', '-4.385347', '102.839390', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Bawah', 'penyangga', '-4.475374', '102.902504', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Maras', 'penyangga', '-4.351321', '102.798567', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ketapang Baru', 'penyangga', '-4.324009', '102.763602', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Seluma', 'penyangga', '-4.124511', '102.514530', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kungkai Baru', 'penyangga', '-4.001347', '102.343318', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sepang', 'penyangga', '-3.922614', '102.305962', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pekik Nyaring', 'penyangga', '-3.729776', '102.274127', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Palik', 'penyangga', '-3.570956', '102.125266', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Serangai', 'penyangga', '-3.436548', '101.932672', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Sebelat', 'penyangga', '-3.226898', '101.614294', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Koto Jaya', 'penyangga', '-2.600426', '101.130450', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Ipuh', 'penyangga', '-3.000724', '101.472208', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Bantal', 'penyangga', '-2.743096', '101.324986', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Banding', 'penyangga', '-5.806678', '105.597407', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bumi Waras', 'penyangga', '-5.443169', '105.279230', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kangkung', 'penyangga', '-5.448993', '105.269313', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kota Karang Raya', 'penyangga', '-5.458021', '105.257059', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kekatang', 'penyangga', '-5.693512', '105.175820', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sukarame', 'penyangga', '-5.682910', '105.240410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Penyandingan', 'penyangga', '-5.701690', '105.073786', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tala Gening', 'penyangga', '-5.491186', '104.595345', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Agung', 'penyangga', '-5.506646', '104.561875', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karang Anyar', 'penyangga', '-5.510496', '104.538384', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjungan', 'penyangga', '-5.553311', '104.508952', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Betung', 'penyangga', '-5.566075', '104.537920', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Way Nipah', 'penyangga', '-5.622855', '104.560363', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karang Brak', 'penyangga', '-5.714384', '104.625920', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sidang Muara Jaya', 'penyangga', '-4.157243', '105.701200', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Badak', 'penyangga', '-3.844797', '105.424646', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Teladas', 'penyangga', '-4.412968', '105.849411', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Burung', 'penyangga', '-4.627000', '105.897440', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Gading Mas', 'penyangga', '-5.359998', '105.812016', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Ratu', 'penyangga', '-5.580258', '105.798556', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kota Jawa', 'penyangga', '-5.633481', '104.301976', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marang', 'penyangga', '-5.378972', '104.078305', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Kota Krui', 'penyangga', '-5.183100', '103.939907', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Balam', 'penyangga', '-5.033853', '103.788706', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Sangkar', 'penyangga', '-3.001410', '106.873410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Celagen', 'penyangga', '-2.873234', '107.015361', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Ketapang', 'penyangga', '-3.008874', '106.449446', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sadai', 'penyangga', '-3.016430', '106.718512', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasir Putih', 'penyangga', '-3.057410', '106.691410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Serdang', 'penyangga', '-2.978910', '106.488120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kepoh', 'penyangga', '-2.854721', '106.607616', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mapur', 'penyangga', '-1.776910', '106.032410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rebo', 'penyangga', '-1.926420', '106.154861', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bintet', 'penyangga', '-1.546579', '105.792961', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Belubang', 'penyangga', '-2.178407', '106.185371', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kurau', 'penyangga', '-2.467910', '106.270410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ketapang', 'penyangga', '-2.103963', '106.132664', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rambat', 'penyangga', '-1.910821', '105.274210', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Limau', 'penyangga', '-1.561996', '105.576401', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Semulut', 'penyangga', '-1.675941', '105.648686', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Niur', 'penyangga', '-2.045141', '105.592177', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Seliu', 'penyangga', '-3.196910', '107.602410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjungrusa', 'penyangga', '-3.013410', '107.619410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mayang', 'penyangga', '-2.657694', '108.132689', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Baru', 'penyangga', '-2.852345', '108.290159', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelarik', 'penyangga', '4.100710', '108.187450', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelarik Barat', 'penyangga', '4.128651', '107.844650', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Belanak', 'penyangga', '2.997069', '107.805283', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sedanau', 'penyangga', '3.848120', '108.071340', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung', 'penyangga', '4.025324', '108.321136', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Selading', 'penyangga', '3.643727', '108.054923', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pala', 'penyangga', '4.711710', '107.980410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sededap', 'penyangga', '3.566781', '108.042697', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sabang Mawang', 'penyangga', '3.635910', '108.123140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sepempang', 'penyangga', '3.969410', '108.393210', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mekar Jaya', 'penyangga', '3.877910', '108.120410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Subi', 'penyangga', '3.018465', '108.864110', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meliah', 'penyangga', '3.099910', '108.874410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Berlian', 'penyangga', '2.531210', '109.051410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Setelung', 'penyangga', '2.549910', '109.078410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Serasan', 'penyangga', '2.510410', '109.025410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Ringau', 'penyangga', '2.498060', '109.052092', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kadur', 'penyangga', '4.738545', '107.978706', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Putih', 'penyangga', '2.978771', '107.767528', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Kelit', 'penyangga', '0.035550', '104.462821', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sekanah', 'penyangga', '-0.021187', '104.599732', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pancur', 'penyangga', '-0.072537', '104.651014', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Penaah', 'penyangga', '0.089171', '104.638100', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belungkur', 'penyangga', '-0.111042', '104.683032', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Berlian', 'penyangga', '-0.618910', '104.428120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Benan', 'penyangga', '-0.100410', '104.415410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mensanak', 'penyangga', '-0.091910', '104.432410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mepar', 'penyangga', '-0.208410', '104.629410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Posek', 'penyangga', '-0.439910', '104.246410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Busung Panjang', 'penyangga', '-0.411084', '104.221799', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tajur Biru', 'penyangga', '0.286285', '104.420639', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Medang', 'penyangga', '-0.099410', '104.417410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Bukit', 'penyangga', '0.288645', '104.424554', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Cempa', 'penyangga', '0.146266', '104.317409', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Duyung', 'penyangga', '0.360355', '104.473581', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pantai Harapan', 'penyangga', '-0.300720', '104.396415', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasir Panjang', 'penyangga', '0.102258', '104.397699', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Temiang', 'penyangga', '0.331728', '104.409751', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Belubang', 'penyangga', '-2.177666', '106.191095', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Baran', 'penyangga', '-0.016410', '104.583410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rejai', 'penyangga', '0.175807', '104.521806', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Lipat', 'penyangga', '1.127385', '104.072248', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senayang', 'penyangga', '-0.015910', '104.584410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Limbung', 'penyangga', '-0.187839', '104.825896', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Pinang', 'penyangga', '-1.193910', '100.468410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelombok', 'penyangga', '-0.205410', '104.635410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mentuda', 'penyangga', '-0.196910', '104.652410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marok Tua', 'penyangga', '-0.639239', '104.358593', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marok Kecil', 'penyangga', '-0.605432', '104.430426', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pekajang', 'penyangga', '-0.196410', '104.653410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Limbung', 'penyangga', '-0.187839', '104.825896', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pekajang', 'penyangga', '-0.204410', '104.637410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelombok', 'penyangga', '-0.195910', '104.654410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Pinang', 'penyangga', '-1.192410', '100.471410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marok Tua', 'penyangga', '-0.639239', '104.358593', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Putik', 'penyangga', '3.365120', '106.325410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Langir', 'penyangga', '3.297352', '106.268238', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Bayur', 'penyangga', '3.271046', '106.264295', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mampok', 'penyangga', '2.960891', '105.716756', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Piasan', 'penyangga', '3.305926', '106.220526', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Maras', 'penyangga', '2.947910', '105.840410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Bini', 'penyangga', '3.146410', '106.247410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belibak', 'penyangga', '3.349620', '106.294410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Piabung', 'penyangga', '3.282956', '106.292365', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pesisir Timur', 'penyangga', '3.201697', '106.264204', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Rewak', 'penyangga', '2.980410', '105.755410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Genting Pulur', 'penyangga', '2.948910', '105.842410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mengkait', 'penyangga', '3.147410', '106.249410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Munjan', 'penyangga', '3.210910', '106.306410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sri Tanjung', 'penyangga', '3.226552', '106.208058', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nyamuk', 'penyangga', '3.227910', '106.340410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Sena', 'penyangga', '3.291410', '106.267410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Asuk', 'penyangga', '3.299910', '106.284410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Telaga Kecil', 'penyangga', '3.148410', '106.251410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Keramut', 'penyangga', '2.991910', '105.698410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Telaga', 'penyangga', '3.140410', '106.235410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Siantan (Sudah disurvei)', 'penyangga', '3.267709', '106.279635', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Belah (Sudah disurvei)', 'penyangga', '3.212410', '106.309410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Telaga', 'penyangga', '3.140910', '106.236410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Siantan (Sudah disurvei)', 'penyangga', '3.267709', '106.279635', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Belah (Sudah disurvei)', 'penyangga', '3.212910', '106.310410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Numbing', 'penyangga', '0.831410', '104.757410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Gelubi', 'penyangga', '0.839910', '104.774410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mapur', 'penyangga', '-1.777410', '106.031410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Malang Rapat', 'penyangga', '0.961910', '104.618410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Bakau', 'penyangga', '0.945410', '104.585410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Busung', 'penyangga', '1.023758', '104.311153', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Sempang', 'penyangga', '1.062120', '104.319140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Berakit', 'penyangga', '1.209234', '104.563061', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sekuni', 'penyangga', '1.024410', '107.563120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Hilir', 'penyangga', '1.032910', '107.580120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kukup', 'penyangga', '1.016410', '107.547120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pengikik', 'penyangga', '1.024910', '107.564120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Mentebung', 'penyangga', '1.033410', '107.581120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Mentebung', 'penyangga', '1.016910', '107.548120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Pinang', 'penyangga', '1.025410', '107.565120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Pinang', 'penyangga', '1.033910', '107.582120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pengikik', 'penyangga', '1.017410', '107.549120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sekuni', 'penyangga', '1.025910', '107.566120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Hilir', 'penyangga', '1.034410', '107.583120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kukup', 'penyangga', '1.017910', '107.550120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Sesah', 'penyangga', '1.056120', '104.307140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sebong Lagoi', 'penyangga', '1.174910', '104.424410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pengudang', 'penyangga', '1.167653', '104.518347', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tembeling Tanjung', 'penyangga', '0.996910', '104.478120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kijang Kota', 'penyangga', '0.852296', '104.599806', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dendun (Sudah disurvei)', 'penyangga', '0.788910', '104.632140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangkil (Sudah disurvei)', 'penyangga', '0.997410', '104.479120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Matang Baru', 'penyangga', '0.757579', '104.513949', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pangkil (Sudah disurvei)', 'penyangga', '0.989410', '104.463120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pengudang', 'penyangga', '1.167653', '104.518347', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sebong Lagoi', 'penyangga', '1.176410', '104.427410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dendun (Sudah disurvei)', 'penyangga', '0.789910', '104.634140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Semembang', 'penyangga', '0.598410', '103.651140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Telaga Tujuh', 'penyangga', '0.606910', '103.668140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Uma', 'penyangga', '1.046076', '103.405960', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pongkar', 'penyangga', '1.028910', '103.442120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batu Limau', 'penyangga', '0.777410', '103.589120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Parit', 'penyangga', '0.961849', '103.437581', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gemuruh', 'penyangga', '0.809410', '103.413410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Kilang', 'penyangga', '0.607910', '103.670140', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tulang', 'penyangga', '0.939935', '103.411454', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Penarah', 'penyangga', '0.739910', '103.544410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Temoyong', 'penyangga', '0.998410', '103.981410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Terung', 'penyangga', '1.151620', '103.898410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bulan Lintang', 'penyangga', '0.990410', '103.965410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karas', 'penyangga', '0.768910', '104.292120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ngenang', 'penyangga', '1.192410', '104.129410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Puluh Buluh', 'penyangga', '0.990910', '103.966410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Piayu', 'penyangga', '3.118700', '97.311200', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ngenang', 'penyangga', '1.192910', '104.130410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kampung Bugis', 'penyangga', '0.966231', '104.474295', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Penyengat', 'penyangga', '0.927886', '104.418480', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Dompak', 'penyangga', '0.903410', '104.491120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Jang', 'penyangga', '0.905249', '104.479678', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senggarang', 'penyangga', '0.935410', '104.445120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Senggarang', 'penyangga', '0.943910', '104.462120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Jang', 'penyangga', '0.905249', '104.479678', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tungkal Ii', 'penyangga', '-0.830527', '103.481674', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Deluk', 'penyangga', '1.471796', '102.419513', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Meskom', 'penyangga', '1.592002', '102.027824', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muntai', 'penyangga', '1.528583', '102.410981', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Alam', 'penyangga', '1.417500', '102.322467', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bekawan', 'penyangga', '0.030654', '103.755554', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panglima Raja', 'penyangga', '-0.280581', '103.713008', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Buluh', 'penyangga', '-0.435231', '103.562916', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Patah Parang', 'penyangga', '-0.546910', '103.422410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanjung Pasir', 'penyangga', '-0.454825', '103.392678', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Batang Tumu', 'penyangga', '0.106073', '103.051889', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Belaras', 'penyangga', '-0.096410', '103.563410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Centai', 'penyangga', '1.044877', '102.559732', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Mekarsari', 'penyangga', '1.012518', '102.420887', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tanah Merah', 'penyangga', '1.146305', '102.799746', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tebing Tinggi Okura', 'penyangga', '0.609488', '101.491731', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk', 'penyangga', '0.538387', '103.187243', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Penyengat', 'penyangga', '0.715958', '102.465203', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Batil', 'penyangga', '1.140376', '102.169967', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sinaboi', 'penyangga', '2.307410', '101.039410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Pulai', 'penyangga', '2.494100', '100.327873', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panipahan', 'penyangga', '2.444210', '100.336039', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Panipahan Darat', 'penyangga', '2.466011', '100.325309', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Hulu', 'penyangga', '2.145839', '100.815007', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Maileppet', 'penyangga', '-1.580910', '99.244120', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Matobe', 'penyangga', '-2.135183', '99.706111', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sikakap', 'penyangga', '-2.756194', '100.251762', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Saliguma', 'penyangga', '-1.430410', '99.195410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Sikabaluan', 'penyangga', '-1.121910', '99.012410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sigapokna Mentawai', 'penyangga', '-0.957618', '98.798678', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tiku Selatan', 'penyangga', '-0.409910', '99.936410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Teluk Kabung Selatan', 'penyangga', '-1.021410', '100.443410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Purus', 'penyangga', '-0.936470', '100.353247', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ampalu', 'penyangga', '-0.604991', '100.115865', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Marunggi', 'penyangga', '-0.655940', '100.154904', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pilubang', 'penyangga', '-0.527982', '100.100678', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Koto Tinggi Kuranji Hilir', 'penyangga', '-0.496017', '100.044088', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Seulayat Ulakan', 'penyangga', '-0.713827', '100.198042', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Manggopoh Palak Gadang Ulakan', 'penyangga', '-0.698066', '100.181896', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Gasan Gadang', 'penyangga', '-0.429715', '99.977852', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Maligi', 'penyangga', '0.060581', '99.626276', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ranah Pasisie', 'penyangga', '0.015852', '99.682313', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sasak', 'penyangga', '0.030939', '99.677522', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Aia Bangih', 'penyangga', '0.241410', '99.417410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Katiagan', 'penyangga', '-0.040910', '99.834410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pulau Rajo Inderapura', 'penyangga', '-2.063882', '100.888410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Air Haji Barat', 'penyangga', '-1.937610', '100.882892', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Pinang', 'penyangga', '-1.195410', '100.465410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ampang Pulai', 'penyangga', '-1.216910', '100.502410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Koto Nan Duo IV Koto Hilie', 'penyangga', '-1.430085', '100.575840', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Asahan Baru', 'penyangga', '3.002680', '99.858580', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Asahan Pekan', 'penyangga', '3.012729', '99.855752', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Jawi-Jawi', 'penyangga', '2.965181', '99.816471', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sei Sembilang', 'penyangga', '2.946859', '99.977586', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nenas Siam', 'penyangga', '3.412435', '99.337071', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bagan Arya', 'penyangga', '3.229085', '99.592136', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Paluh Sibaji', 'penyangga', '3.671372', '98.908083', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kelambir', 'penyangga', '3.681835', '98.852390', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Nelayan Indah', 'penyangga', '3.748216', '98.687938', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kwala Serapuh', 'penyangga', '4.009183', '98.454575', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Secanggang', 'penyangga', '3.856582', '98.538424', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Sorkam', 'penyangga', '1.947700', '98.599200', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kedai Gedang', 'penyangga', '2.010107', '98.417686', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Baru Batahan', 'penyangga', '0.381561', '99.170797', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar V Natal', 'penyangga', '0.544986', '99.120453', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Tabuyung', 'penyangga', '0.898410', '98.991410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Labuhan Bazau', 'penyangga', '-0.083910', '98.458410', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bale-bale Sibohou', 'penyangga', '-0.074219', '98.436513', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Majino Lorang', 'penyangga', '-0.003805', '98.224343', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Teluk Dalam', 'penyangga', '0.568616', '97.819499', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bawozihono', 'penyangga', '0.729600', '97.883330', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Siwalu Banua', 'penyangga', '0.789842', '97.890221', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Afia', 'penyangga', '1.369674', '97.557152', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Laira', 'penyangga', '1.093133', '97.808972', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Bozihona', 'penyangga', '1.090682', '97.835774', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Afulu', 'penyangga', '1.270690', '97.263424', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Faekhuna''''A', 'penyangga', '1.176667', '97.308126', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Pasar Lahewa', 'penyangga', '1.404683', '97.182151', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Siofa Banua', 'penyangga', '1.443711', '97.493507', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Simpang Tiga Makmur', 'penyangga', '-3.326676', '105.899794', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Kuala Sungai Pasir', 'penyangga', '-3.645768', '105.806790', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Lumpur', 'penyangga', '-3.402548', '105.800098', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Batang', 'penyangga', '-2.652782', '105.376788', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Juru Taro', 'penyangga', '-2.373712', '105.181083', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Upang Makmur', 'penyangga', '-2.537162', '104.950789', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Karang Anyar', 'penyangga', '-2.548583', '104.766944', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Ringin Agung', 'penyangga', '-2.269064', '104.559897', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Kelingi', 'penyangga', '-3.084679', '103.233393', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Muara Rengas', 'penyangga', '-2.941213', '103.303092', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Burai', 'penyangga', '-3.268988', '104.608953', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Seri Kembang', 'penyangga', '-3.625941', '104.579363', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sunur', 'penyangga', '-3.534769', '104.533145', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Sungai Sibur', 'penyangga', '-3.800900', '105.900924', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;
INSERT INTO knmps (name, jenis_knmp, lat, long, status, created_at, updated_at) VALUES ('KNMP Simpang Tiga Jaya', 'penyangga', '-3.284303', '106.005408', 'on_track', NOW(), NOW()) ON CONFLICT DO NOTHING;